---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
spec:
  selector:
    app: {{ .Release.Name }}-db
  clusterIP: None
  ports:
    - protocol: TCP
      port: {{ .Values.dbPort }}



---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-db
spec:
  serviceName: {{ .Release.Name }}-db
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - name: {{ .Values.dbPortName }} 
              containerPort: {{ .Values.dbPort }} 
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secret
          volumeMounts:
            - name: {{ .Release.Name }}-db
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name }}-db
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
