---

- name: Create k8s master security group 
  ec2_group:
    name: k8s-master-sg 
    region: "{{ region_name }}"
    description: k8s master sg 
    state: present
    rules:
    - proto: all
      cidr_ip: 0.0.0.0/0 
    rules_egress:
    - proto: all
      cidr_ip: 0.0.0.0/0
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    security_token: "{{ security_token }}"

- name: Start k8s master 
  ec2:
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_flavour }}"
    image: "{{ ami_id }}"
    wait: yes
    instance_tags:
      Name: k8smaster 
      name: k8smaster 
    region: "{{ region_name }}"
    exact_count: 1
    count_tag:  
      name: k8smaster 
    group: k8s-master-sg 
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    security_token: "{{ security_token }}"
  register: ec2_k8s_master

- name: Allocate master elastic IP 
  ec2_eip:
    device_id: "{{ ec2_k8s_master.tagged_instances[0].id }}"
    region: "{{ region_name }}"
    in_vpc: yes
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    security_token: "{{ security_token }}"
  register: eip

- name: output the IP
  debug:
    var: eip 

- name: Add master to k8s_master group
  add_host:
    hostname: "{{ ec2_k8s_master.tagged_instances[0].public_ip }}"
    groupname: k8s_master
