---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  clusterIP: None
  ports:
    - protocol: TCP
      port: {{ .Values.dbPort }} 
