---

- name: Create webserver security group 
  ec2_group:
    name: webservers 
    region: "{{ region_name }}"
    description: webserver security group
    state: present
    rules:
    - proto: tcp
      from_port: 80 
      to_port: 80
      cidr_ip: 0.0.0.0/0
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 0.0.0.0/0
    rules_egress:
    - proto: 80
      to_port: 80
      cidr_ip: 0.0.0.0/0
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    security_token: "{{ security_token }}"

- name: Start k8s master 
  ec2:
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_flavour }}"
    image: "{{ ami_id }}"
    wait: yes
    instance_tags:
      Name: k8smaster 
      name: k8smaster 
    region: "{{ region_name }}"
    exact_count: 1
    count_tag:  
      name: k8smaster 
    group: webservers 
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    security_token: "{{ security_token }}"
  register: ec2_k8s_master

- name: debug ec2_k8s_master
  debug: var=ec2_k8s_master

- name: Set k8s master elastic ip 
  ec2_eip:
    region: "{{ region_name }}"
    in_vpc: yes
    reuse_existing_ip_allowed: yes
    state: present
    device_id: "{{ ec2_k8s_master.tagged_instances[0].id }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    security_token: "{{ security_token }}"
  register: eip

- name: Add master to k8s_master group 
  add_host:
    hostname: "{{ ec2_k8s_master.tagged_instances[0].public_ip }}"
    groupname: k8s_master
