---

- name: Create EC2 Security Group 
  ec2_group:
    name: "{{ sg_name }}" 
    region: "{{ region_name }}"
    description: cluster security group
    state: present
    rules:
    - proto: tcp
      from_port: 80 
      to_port: 80
      cidr_ip: 0.0.0.0/0
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 0.0.0.0/0
    - proto: tcp
      from_port: 6443
      to_port: 6443
      cidr_ip: 0.0.0.0/0
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    security_token: "{{ security_token }}"

- name: Add EC2 Cluster Master 
  ec2:
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_flavour }}"
    image: "{{ ami_id }}"
    wait: yes
    instance_tags:
      Name: master 
    region: "{{ region_name }}"
    group: "{{ sg_name }}"
    count_tag:  
      Name: master 
    exact_count: 1
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    security_token: "{{ security_token }}"
  register: master

- name: Allocate Master Elastic IP 
  ec2_eip:
    state: present
    device_id: "{{ master.tagged_instances[0].id }}"
    region: "{{ region_name }}"
    in_vpc: yes
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    security_token: "{{ security_token }}"
  register: eip

- name: Show Master Elastic IP
  debug:
    var: eip 

- name: Add master to master group
  add_host:
    hostname: "{{ eip.public_ip }}"
    groupname: master

- name: Create EC2 Load Balancer 
  ec2_elb_lb:
    name: app-load-balancer
    state: present
    region: "{{ region_name }}"
    zones: "{{ region_zones }}"
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    security_token: "{{ security_token }}"
  register: elb

- name: Add EC2 Cluster Worker Nodes
  ec2:
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_flavour }}"
    image: "{{ ami_id }}"
    wait: yes
    instance_tags:
      Name: "worker-{{ item }}" 
    region: "{{ region_name }}"
    group: "{{ sg_name }}"
    count_tag:  
      Name: "worker-{{ item }}" 
    exact_count: 1
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    security_token: "{{ security_token }}"
  with_items: ['1', '2']
  register: ec2_workers

- name: Show workers 
  debug:
    var: ec2_workers 

- name: Add Cluster Worker Nodes to Worker Group
  add_host:
    groupname: workers
    hostname: "{{ item.tagged_instances[0].public_ip }}"
  with_items: "{{ ec2_workers.results }}"  

