---

kind: Service
apiVersion: v1
metadata:
  name: {{.Release.Name}}-frontend
spec:
  type: NodePort
  selector:
    name: {{.Release.Name}}-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30036
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{.Release.Name}}-frontend
spec:
  replicas: {{.Values.hpaMinReplicas}}
  selector:
    matchLabels:
      app: {{.Release.Name}}-frontend
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-frontend
    spec:
      containers:
        - name: cont1
          image: leaddevops/kubeserve:v2
	  ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 10m
