- hosts: localhost
  gather_facts: no
  vars_files:
        - cred.yml
  tasks:
    - name: Provision EC2 
      include_role:
        name: ec2

- hosts: k8s_master
  gather_facts: no
  tasks:
    - name: Running K8s Master Role
      include_role:
        name: k8s_master

