- hosts: localhost
  gather_facts: no
  environment:
    AWS_ACCESS_KEY: "{{access_key}}"
    AWS_SECRET_KEY: "{{secret_key}}"
    SECURITY_TOKEN: "{{security_token}}"

  tasks:
    - name: Running Cluster EC2 Role
      include_role:
        name: ec2


- hosts: master
  gather_facts: no
  tasks:
    - name: Running Kubernetes Master Role
      include_role:
        name: master

- hosts: workers
  gather_facts: no
  tasks:
    - name: Running Kubernetes Worker  Role
      include_role:
        name: worker
