---
# tasks file for cluster worker node 
- name: Add kubeadm Repositories on Worker Node
  yum_repository:
    name: kube
    description: Kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    enabled: 1
    gpgcheck: 1
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Installing docker & kubeadm on Worker
  package:
    name:
      - docker
      - kubeadm
      - iproute-tc
    state: present

- name: Staring & enabling docker & kubelet on Worker 
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ service_names }}"

- name: Updating docker cgroup on slave
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
      "exec-opts": ["native.cgroupdriver=systemd"]
      }

- name: Restart docker on Worker 
  service:
    name: docker
    state: restarted

- name: Updating IP tables on slave 
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: Reloading sysctl on Worker 
  command: sysctl --system

- name: Joining the cluster 
  command: "{{ hostvars[groups['master'][0]]['token']['stdout'] }}"

- name: Cleaning Caches on RAM
  shell: echo 3 > /proc/sys/vm/drop_caches
