apiVersion: rbac.authorization.k8s.io/v1

kind: RoleBinding
metadata:
  name: pod-crud
subjects:
- kind: User
  name: myuser
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-crud
  apiGroup: rbac.authorization.k8s.io

